name: Create GitHub release
inputs:
  changelog:
    required: true
    type: string
  release_version:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ inputs.release_version }}
        body: ${{ inputs.changelog }}
