name: Run tests
runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install dependencies
      run: make install
      shell: sh

    - name: Run tests
      run: make tests
      shell: sh
