name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-tests
